### ISSUE TITLE
Different algorithms are implemented depending on target pointer width

### ISSUE THREAD

**Issue by riking** [shank03/XORCryptor-Rust#3]
This crate actually contains two (weak) encryption algorithms, but only conditionally compiles one of the two based on the target's pointer width.

Both 32-bit and 64-bit machines should have access to both algorithm implementations.

**Comment by shank03** [comment]
The algorithm was same. The 64-bit implementation was applying the algorithm in the group of 8 bytes whereas 32-bit and lower implementation was applying the algorithm on each byte.

Could have been useful for embedded or IOT stuffs, but anyway I have remove other implementations and now only 64-bit version supported.
